server:
  port: 80
#  servlet:
#    context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: touwen
    url: jdbc:mysql://127.0.0.1/test?characterEncoding=utf-8&useSSL=false
    #password: admin
    #url: jdbc:mysql://127.0.0.1/springboot?characterEncoding=utf-8&useSSL=false password: admin

    #打印sql语句
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

wechat:
  mpAppID: wx7a7ba703beebd371
  mpAppSecret: 56e1db359767a1349dc9f125a61a9f7c
  mchId: 123
  mchKey: 123
  #证书
  keyPath: 123
  #异步通知地址，必须
  notifyUrl: 123

wechaturl:
  wechatMpAuthorize: http://denny.ngrok.xiaomiqiu.cn
  wechatOpenAuthorize: 123
  sell: 123





