server:
  port: 80
  servlet:
    context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: touwen
    url: jdbc:mysql://127.0.0.1/test?characterEncoding=utf-8&useSSL=false
    #password: admin
    #url: jdbc:mysql://127.0.0.1/springboot?characterEncoding=utf-8&useSSL=false password: admin

    #打印sql语句
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

wechat:
  mpAppID:
  mpAppSecret:



